#
# Copyright (c) 2021 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: carts
spec:
  cluster: SockShop
  role: Carts
  replicas: 1
  image: ghcr.io/oracle/coherence-spring-sockshop-carts:latest
  env:
    - name: TRACING_HOST
      value: "jaeger-collector"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
    - name: COHERENCE_SERVICE_NAME
      value: "Carts"
    - name: APM_ATTRIBUTES_K8S_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: APM_ATTRIBUTES_K8S_NAMESPACE_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: APM_ATTRIBUTES_K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  application:
    main: com.oracle.coherence.examples.sockshop.spring.carts.CartsApp
    args:
      - "--port=8080"
      - "--spring.zipkin.enabled=false"
      - "--coherence.server.startup-timeout=5m"
      - "--spring.jmx.enabled=true"
      - "--server.tomcat.mbeanregistry.enabled=true"
  jvm:
    memory:
      heapSize: 2g
    args:
      - "-javaagent:/etc/provisioned-apm/oracle-apm-agent/bootstrap/ApmAgent.jar"
  coherence:
    metrics:
      enabled: true
  ports:
    - name: http
      port: 8080
      service:
        name: carts
        port: 80
      serviceMonitor:
        enabled: true
        path: /actuator/prometheus
    - name: metrics
      serviceMonitor:
        enabled: true
  volumeMounts:
    - name: provisioned-apm
      mountPath: /etc/provisioned-apm
    - name: apm-attributes-k8s
      mountPath: /etc/apm-attributes-k8s      
  initContainers:
    - name: init-container
      image: "ap-chuncheon-1.ocir.io/apackrsct01/apm-java-agent-installer:1.7.2733"
      command: ["sh", "-c", "java -jar ./apm-java-agent-installer-1.7.2733.jar provision-agent -service-name=carts -destination=/etc/shared -private-data-key=$(PRIVATE_DATA_KEY) -data-upload-endpoint=$(DATA_UPLOAD_ENDPOINT)"]
      volumeMounts:
      - name: provisioned-apm
        mountPath: /etc/shared
  volumes:
    - name: provisioned-apm
      emptyDir: {}
    - name: apm-attributes-k8s
      downwardAPI:
        items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations         